### PR TITLE
Update download page with Game Engine description

### PR DESCRIPTION
**Pull request by SeanAverS**
Updated the download page with a description of the game engine (Ren'py)

- Used styles from `Home.css` to maintain consistency with the existing page styles

This change addresses #25, which was dependent on #28. I noticed that @jonana-split has recently solved #28, so that's why I'm submitting this pull request.

### CODE REVIEW

**Comment by AntonCSalvador** [comment]
@SeanAverS Hey so in the recent changes to the Home page on the main repo we changed the font and such. If you can apply those changes too that would be good. I think there is also a current bug on the main download page where it is overriding the Download.css?

**Comment by SeanAverS** [comment]
Will get to work on those changes 👍

**Comment by SeanAverS** [comment]
Screenshot 2024-06-24 172848


Hello @AntonCSalvador,  

I noticed in a recent PR these styles in  `Home.js` responsible for centering and styling the elements in `Download.js` were removed.

Per your comment, reapplying these removed styles re-centers the elements.  I think this is where the overriding issue comes from.

I think moving the removed styles to `Download.js` would make it easier to find and maintain, and I can also change the font there to align with your most recent changes to the home page. 

Please let me know if you have any suggestions 😄

**Comment by AntonCSalvador** [comment]
Hey @SeanAverS your suggested changes sound good! Try those out and I will review them after! Thank you for your hard work

**Pull request closed without merging**
