### PR TITLE
Changed File Structure and Added README

### PR DESCRIPTION
**Pull request by AntonCSalvador**
Moved all the files up one so they dont have to cd into the website folder and added a readme and a .gitignore for node_modules so they dont have to clone with everything

### CODE REVIEW

**Comment by Xa-el** [comment]
No LGTM = Pull request not accepted

**Comment by AntonCSalvador** [comment]
Mb @Xa-el

**Comment by AntonCSalvador** [comment]
LGTM

**Comment by JMalegni** [comment]
LGTM, I would appreciate it if you keep me updated on any additional dependencies you add so I can easily test this. Also I am not admin  here so you can jut merge it

**Pull request merged**
