### PR TITLE
Issue #35: Redesign of Homepage Carousel

### PR DESCRIPTION
**Pull request by PhillipsCorey**
Fixes ufosc/BytesOfLoveWebsite#35.
Fixes ufosc/BytesOfLoveWebsite#36.

## Features:
1. A row of "nav buttons" now exists along the bottom of the carousel so you can jump around freely!
2. The left and right arrow buttons have been visually and mechanically reworked.
3. *Basic animations, oh my!*
4. Carousel contents are faded during transistions, and the buttons have functions to manipulate this.
5. Images are preloaded now, to hopefully reduce carousel oddities.
6. Tried my very best to make the visual theme of the carousel consistent, found a lot of "zombie CSS" laying around that wasn't doing anything and got rid of it.

## Affected Files:
- `src/Carousel/Carousel.js`
  - Added the new `Carousel_Navigation_Buttons`, which creates a series of black, clickable buttons to swing you through the carousel. The number of buttons is based on the length of the images array in defined in the same file. 
  - `Carousel` now takes in `fade`, a boolean React hook to control the fading of the content contained within the carousel.
  - Spaced out the in-line CSS.
  - Used a few ternary operators and transistion CSS labels to make the carousel contents fade when navigation buttons are interacted with.
  - Made new alts of `arrow_left` and `arrow_right` to support the new color style of the carousel. Attached them to the buttons.
  - Some image preloading nonsense has been added to make the carousel lag less, hopefully.
- `src/Carousel/Carousel.css`
  - Lots of new CSS, mostly affecting `left-button`, `right-button`, and the new `nav-button`.
- `src/Home/Home.js`
  - In order to follow the repo's current style, all new functions which work the carousel's new funcitonality have been added here.
  - A new function, `handleButtonNav` is responsible for the (currently six) navigation buttons at the bottom of the carousel.
  - Both the new `handleButtonNav` and the old `handleRotate*` functions have been wrapped in new functions, titled `handleFadeNav` and `handleFadeArrows`.
    - These fade functions are what get passed to navigation buttons in `Carousel.js` now, they handle both fading and managing the array index of the carousel.
    - `handleFadeNav` is passed DOWN to `Carousel.js` to be assembled, while `handleFadeArrows` is assembled in `Home.js`. This is because each nav button has a unique index that cannot be easily accessed from the scope of `Home.js`, but the latter has no such limitation.
  - Added `Carousel_Navigation_Buttons` to the bottom of the Carousel group.
- `public/images/arrow_left_alt.png` and `public/images/arrow_right_alt.png`
  - simple recolors of the original `arrow_left` and `arrow_right` to fit the new visual style of the carousel.
  - the old versions are still present in the files, should anything need to be reverted!
  - `arrow_left` has an ugly, white border around it from improper background removal. I tried my best to get rid of it in the alt.

### CODE REVIEW

**Comment by AntonCSalvador** [comment]
Hey @PhillipsCorey ! This is actually insanely good and way better than I was expecting. I just have a few more fixes. 

The main thing is if you can make the arrows not have the black around and just have the color of the background instead of black.

Also,
mobileVIewHome
 the mobile view of the carousel is a LITTLE scuffed and if this can be fixed it will be PERFECT.

**Comment by AntonCSalvador** [comment]
Animations are fire btw

**Comment by PhillipsCorey** [comment]
Hi Anton,

The primary issue associated with the carousel on mobile seems to be that a lot of elements on the page were overflowing into white space on mobile layouts:

image


This takes up valuable width by forcing white-space onto the page. This isn't necessarily the carousel's problem, but I fixed it regardless. Now, a lot of the page's text (carousel banner, download text, etc.) is dependent on calculations relative to the size of the screen:

image
image

This gives the carousel much more space on mobile. Additionally, I made a few more changes to how things on the carousel are sized. This makes things larger on laptops and smaller on phones by wasting less white space:

image
image

These changes nearly fix issue number 37, but the scroll bar is still there, and I'm not willing to keep delving into what else is overflowing. I have office hours in eight minutes. Ultimately, I hope this updates are satisfactory. Thanks!

**Comment by AntonCSalvador** [comment]
Hey @PhillipsCorey ITS ALMOST PERFECT! Thanks for implementing all of the requested changes,
one small nitpick can be seen in the following images:
caro2
caro1
when the description of the image goes to the next line, it pushes down the circles. This could probably be fixed with flexbox alignment or absolute positioning or other methods. let me know if you have any questions!

**Comment by AntonCSalvador** [comment]
LGTM! LETS GET THE MONEY. Great work @PhillipsCorey

**Comment by PhillipsCorey** [comment]
🚀

**Pull request merged**
