### PR TITLE
fixed download links for Mac and Linux

### LINKED ISSUE #15: Fix Download Links
The buttons to download the game currently only work on Windows. All three links are the same, so if Mac or Linux users try to download the game it will say it is not compatible with their system. 

So the links for Mac and Linux download buttons need to be fixed. Changes to the code need to be made wherever these buttons appear which is in Home.js and Download.js

### PR DESCRIPTION
**Pull request by jonana-split**
This change resolves #15

The download links for Mac and Linux have been fixed.

I used the most recent version of the game via the [BytesOfLove Repo](https://github.com/ufosc/VisualNovel) to generate these links in Ren'Py and uploaded them to Google Drive, where they can now be downloaded. 

Windows link was not updated as that was not asked, but I can definitely do that if what I've done here is alright.

### CODE REVIEW

**Comment by AntonCSalvador** [comment]
LGTM, if you can do the Windows link too I think it will be good to merge!

**Comment by jonana-split** [comment]
@AntonCSalvador Will do! I'll get to that now. I also noticed that the text color in the About and Help screens is a bit dark in this version of the game. I'm not quite sure how that would be altered but I wanted to let you know!

**Comment by AntonCSalvador** [comment]
@jonana-split ACTUALLY sorry can we review the other PRs in the actual BOL game first before you make the download links?

**Comment by jonana-split** [comment]
@AntonCSalvador yeah ofc! just lmk when ur good to go and i can make the links updated again

**Comment by AntonCSalvador** [comment]
Thanks for your hard work, it is really appreciated! I'll ping you here when I get the update from our main PR person for the Bytes Of Love main repo

**Comment by jonana-split** [comment]
Its no problem at all! Love what you guys are making here :D and okay sounds good!

**Comment by zeim839** [comment]
Why use a Google Drive URL? Create a GitHub release and just link users to the releases page. That way, you don't have to update the URL every time the game is updated.

Bytes of Love releases page: https://github.com/ufosc/BytesOfLoveWebsite/releases
GitHub Releases docs: https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases

**Pull request closed without merging**
