### PR TITLE
Implemented Tailwind, added "BOL Home Video", added music button in corner, and working downloads

### PR DESCRIPTION
**Pull request by AntonCSalvador**
I added the music button in the corner so people can hear our intro music throughout the site and the download buttons with working links. We can def change the colors, it is temporary for now.

### CODE REVIEW

**Comment by AntonCSalvador** [comment]
LGTM

**Comment by AntonCSalvador** [comment]
Make sure you npm install again for tailwind

**Comment by Xa-el** [comment]
There's a bug where if you go to the site and click the unmute button, nothing will play until you click one of the other tabs, click back to home and unmute. This happens on both Chrome and Opera GX . However, for some reason, when using Firefox this bug doesn't happen and the site functions as normal. Other than that LGTM.

**Comment by AntonCSalvador** [comment]
I'll work on it rn

**Comment by Xa-el** [comment]
Bug fixed on my machine LGTM

**Pull request merged**
